{
 "title": "Timescaledb Metrics",
 "description": "A common dashboard of telegraf only applications",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": "timescaledb" },
   {
    "name": "instance_name",
    "label": "Instance Name",
    "query": "up{project=\"$project\"}"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "postgresql_datid{project=\"$project\"}"
   }
  ]
 },
 "panels": [
  { "title": "Instance Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(up{project=\"$project\",instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(system_n_cpus{project=\"$project\", instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "CPU count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(system_n_cpus{project=\"$project\",instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(mem_total{project=\"$project\",instance_name=~\"$instance_name\"}/1000000000.0)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "min(system_uptime{project=\"$project\",instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "Last deployment time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(process_start_time_seconds{project=\"$project\",instance_name=~\"$instance_name\"}*1000)"
    }
   ]
  },
  { "title": "Server Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - min_over_time(cpu_usage_idle{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}[5m])",
     "legendFormat": "cpu_usage_total - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_iowait{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_iowait - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_guest{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_guest - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_guest_nice{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_guest_nice - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_irq{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_irq - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_nice{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_nice - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_softirq{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_softirq - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_steal{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_steal - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_system{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_system - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_user{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_user - {{instance_name}} - {{private_ip}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}} "
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "postgresql_replication_replication_lag{project=\"timescaledb\"}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 12 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "postgresql_replication_replication_lag{project=\"$project\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}} "
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load1{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "System Load [1] - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "system_load5{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "System Load [5] - {{instance_name}} - {{private_ip}}"
    }
   ]
  },
  { "title": "Disk Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diskio_iops_in_progress{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}} - {{name}}"
    }
   ]
  },
  {
   "title": "Disk write bytes per min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(diskio_write_bytes{project=\"$project\",instance_name=~\"$instance_name\"}[1m])",
     "legendFormat": "{{instance_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "Disk read bytes per min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(diskio_read_bytes{project=\"$project\",instance_name=~\"$instance_name\"}[1m])",
     "legendFormat": "{{instance_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_total{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}} - {{device}} - {{path}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_used_percent{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}} - {{device}} - {{path}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}}"
    }
   ]
  },
  { "title": "Network Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Network sent-recv bytes per min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(net_bytes_sent{project=\"$project\",instance_name=~\"$instance_name\"}[1m])",
     "legendFormat": "Net Bytes Sent - {{instance_name}} - {{interface}}"
    },
    {
     "expr": "irate(net_bytes_recv{project=\"$project\",instance_name=~\"$instance_name\"}[1m])",
     "legendFormat": "Net Bytes Recv - {{instance_name}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Network sent-recv packets per min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(net_packets_sent{project=\"$project\",instance_name=~\"$instance_name\"}[1m])",
     "legendFormat": "Net Packets Sent - {{instance_name}} - {{interface}}"
    },
    {
     "expr": "irate(net_packets_recv{project=\"$project\",instance_name=~\"$instance_name\"}[1m])",
     "legendFormat": "Net Packets Recv - {{instance_name}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Network sent-recv err/packt-drops per min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(net_err_in{project=\"$project\",instance_name=~\"$instance_name\"}[1m])",
     "legendFormat": "Net Err In - {{interface}}"
    },
    {
     "expr": "irate(net_err_out{project=\"$project\",instance_name=~\"$instance_name\"}[1m])",
     "legendFormat": "Net Err Out - {{interface}}"
    },
    {
     "expr": "irate(net_drop_in{project=\"$project\",instance_name=~\"$instance_name\"}[1m])",
     "legendFormat": "Net Drop In - {{interface}}"
    },
    {
     "expr": "irate(net_drop_out{project=\"$project\",instance_name=~\"$instance_name\"}[1m])",
     "legendFormat": "Net Drop Out - {{interface}}"
    }
   ]
  },
  { "title": "Connection Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Total Connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 44 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(postgresql_numbackends{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_numbackends{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Transactions Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Transaction Commits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_xact_commit{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transaction Rollbacks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_xact_rollback{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_deadlocks{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Tuples Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Tuples Fetched From Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_tup_fetched{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Tuples Returned From Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_tup_returned{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Tuples Deleted From Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_tup_deleted{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Tuples Inserted From Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_tup_inserted{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Tuples Updated From Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_tup_updated{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Queries Cancelled due to Conflicts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_conflicts{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Disk Block Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Block Cache Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_blks_hit{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Disk Block Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_blks_read{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Block Write Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_blk_write_time{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temp Bytes Created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_temp_bytes{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temp Files Created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_temp_files{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Block Read Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_blk_read_time{project=\"$project\",instance_name=~\"$instance_name\",datname=~\"$database\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}