{
 "title": "Redis Metrics",
 "description": "Redis + Sentinel cluster dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": "redis" },
   {
    "name": "instance_name",
    "label": "Instance Name",
    "query": "system_uptime{project=\"$project\"}"
   }
  ]
 },
 "panels": [
  { "title": "Instance Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(up{project=\"$project\",instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(system_n_cpus{project=\"$project\", instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "CPU count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(system_n_cpus{project=\"$project\",instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mem_total{project=\"$project\",instance_name=~\"$instance_name\"}/1000000000.0)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 1 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "min(system_uptime{project=\"$project\",instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "Last deployment time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(process_start_time_seconds{project=\"$project\",instance_name=~\"$instance_name\"}*1000)"
    }
   ]
  },
  { "title": "Redis Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Role",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "name",
   "targets": [
    {
     "expr": "redis_uptime{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{replication_role}}"
    }
   ]
  },
  {
   "title": "Sentinel count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(procstat_lookup_running{systemd_unit=\"redis-sentinel.service\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_used_memory{project=\"$project\",instance_name=~\"$instance_name\"}  / redis_total_system_memory{project=\"$project\",instance_name=~\"$instance_name\"} )"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "cpu_usage_user{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\"}"
    }
   ]
  },
  {
   "title": "Slave Replication Lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_replication_lag{project=\"redis\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}} "
    }
   ]
  },
  {
   "title": "Slave Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_slaves{project=\"$project\",instance_name=~\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_clients{project=\"$project\",instance_name=~\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(redis_uptime{project=\"$project\",instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "Pubsub channels",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(redis_pubsub_channels{project=\"$project\", instance_name=~\"$instance_name\"})"
    }
   ]
  },
  { "title": "Persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "DB Loading Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(redis_loading{project=\"$project\",instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "RDB last save time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(redis_rdb_last_save_time{project=\"$project\",instance_name=~\"$instance_name\"}*1000)"
    }
   ]
  },
  {
   "title": "Changes since last RDB save",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(redis_rdb_changes_since_last_save{project=\"$project\", instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "RDB last BGSAVE status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 11 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "redis_uptime{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{rdb_last_bgsave_status}}"
    }
   ]
  },
  {
   "title": "AOF last rewrite time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_aof_last_rewrite_time_sec{project=\"$project\",instance_name=~\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "AOF current rewrite time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_aof_current_rewrite_time_sec{project=\"$project\",instance_name=~\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "AOF last BGWRITE status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "redis_uptime{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{aof_last_bgrewrite_status}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Active Defrag Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_active_defrag_running{project=\"$project\", instance_name=~\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "Mem fragmentation Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_mem_fragmentation_bytes{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}} "
    }
   ]
  },
  {
   "title": "Active Defrag Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_active_defrag_hits{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{active-defrag-hits}} "
    },
    {
     "expr": "redis_active_defrag_misses{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{active-defrag-misses}} "
    },
    {
     "expr": "redis_active_defrag_key_hits{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{active-defrag-key-hits}} "
    },
    {
     "expr": "redis_active_defrag_key_misses{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{active-defrag-key-misses}} "
    }
   ]
  },
  {
   "title": "Net Input-Output Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_total_net_input_bytes{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{net-input-bytes}} "
    },
    {
     "expr": "redis_total_net_output_bytes{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{net-output-bytes}} "
    }
   ]
  },
  {
   "title": "Mem Frag Ratio",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{project=\"$project\", instance_name=~\"$instance_name\"}"
    }
   ]
  },
  { "title": "Keyspace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Keys per database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_keyspace_keys{project=\"$project\",instance_name=~\"$instance_name\"}) by (database)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Keyspace misses",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(redis_keyspace_misses{project=\"$project\", instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(redis_expired_keys{project=\"$project\", instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "Keyspace Hit-rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_keyspace_hitrate{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}} "
    }
   ]
  },
  {
   "title": "Keyspace  Hits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(redis_keyspace_hits{project=\"$project\", instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "Evicted Keys",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(redis_evicted_keys{project=\"$project\", instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "Cmd call stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_cmdstat_calls{project=\"$project\",instance_name=~\"$instance_name\"}) by (command)",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "max(redis_total_commands_processed{project=\"$project\", instance_name=~\"$instance_name\"})",
     "legendFormat": "{{total}}"
    }
   ]
  },
  {
   "title": "Keyspace avg TTL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_keyspace_avg_ttl{project=\"$project\",instance_name=~\"$instance_name\"}) by (database)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "OS Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - min_over_time(cpu_usage_idle{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}[5m])",
     "legendFormat": "cpu_usage_total - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_iowait{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_iowait - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_guest{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_guest - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_guest_nice{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_guest_nice - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_irq{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_irq - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_nice{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_nice - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_softirq{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_softirq - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_steal{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_steal - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_system{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_system - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "cpu_usage_user{project=\"$project\",instance_name=~\"$instance_name\",cpu=\"cpu-total\",alertname=\"\"}",
     "legendFormat": "cpu_usage_user - {{instance_name}} - {{private_ip}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}} "
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load1{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "System Load [1] - {{instance_name}} - {{private_ip}}"
    },
    {
     "expr": "system_load5{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "System Load [5] - {{instance_name}} - {{private_ip}}"
    }
   ]
  },
  { "title": "Disk Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Total Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_total{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}} - {{device}} - {{path}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_used_percent{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}} - {{device}} - {{path}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diskio_iops_in_progress{project=\"$project\",instance_name=~\"$instance_name\"}",
     "legendFormat": "{{instance_name}} - {{private_ip}} - {{name}}"
    }
   ]
  },
  {
   "title": "Disk write bytes per 5 mins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(diskio_write_bytes{project=\"$project\",instance_name=~\"$instance_name\"}[5m])",
     "legendFormat": "{{instance_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "Disk read bytes per 5 mins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(diskio_read_bytes{project=\"$project\",instance_name=~\"$instance_name\"}[5m])",
     "legendFormat": "{{instance_name}} - {{name}}"
    }
   ]
  }
 ]
}